id: proxmox
name: Proxmox Cluster
schedule:
  interval: 60s
timeout: 3s
freshness:
  maxAge: 180s
mqtt:
  enabled: true
  topic: home/proxmox
  device:
    name: Proxmox Cluster
    manufacturer: Custom
    model: Proxmox Cluster
